# basic options,i can say whatever i want
title: Data Sanctuary
author: Github User
email: your-email@domain.com
description: A wonderful site
twitter_username: jewelzgh
github_username: jewelz_B

#Build settings
markdown: kramdown
theme: minima
